<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
	  <Folder Include="Assets\" />
	  <Folder Include="Content\Accessories\" />
	  <Folder Include="Content\Buffs\" />
	  <Folder Include="Content\Items\Materials\" />
	  <Folder Include="Content\Weapons\Magic\Projectiles\" />
	  <Folder Include="Content\Weapons\Ranged\Projectiles\" />
	  <Folder Include="Content\Dust\" />
	</ItemGroup>

</Project>